apiVersion: v1
kind: Namespace
metadata:
  name: blue-green-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green-app-blue
  namespace: blue-green-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-green-app
      color: blue
  template:
    metadata:
      labels:
        app: blue-green-app
        color: blue
    spec:
      containers:
        - name: app
          image: blue-green-app:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: COLOR
              value: "blue"
            - name: VERSION
              value: "1.0.0"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green-app-green
  namespace: blue-green-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-green-app
      color: green
  template:
    metadata:
      labels:
        app: blue-green-app
        color: green
    spec:
      containers:
        - name: app
          image: blue-green-app:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: COLOR
              value: "green"
            - name: VERSION
              value: "1.0.0"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-app
  namespace: blue-green-demo
spec:
  type: ClusterIP
  selector:
    app: blue-green-app
    color: blue   # ðŸ‘ˆ start on BLUE
  ports:
    - name: http
      port: 80
      targetPort: 8080